services:
  - type: web
    name: brewhouse-server
    env: node
    region: ohio
    plan: free
    buildCommand: "npm install && npm run db:generate"
    startCommand: "npm run start"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
    rootDir: server
